apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"todo-app-dep","namespace":"project"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"todo-app"}},"template":{"metadata":{"labels":{"app":"todo-app"}},"spec":{"containers":[{"env":[{"name":"PORT","value":"8080"},{"name":"GIN_MODE","value":"release"}],"image":"zhubao/todo-app:latest","name":"todo-app","ports":[{"containerPort":8080}],"volumeMounts":[{"mountPath":"/usr/src/app/files","name":"shared-image"}]}],"volumes":[{"name":"shared-image","persistentVolumeClaim":{"claimName":"image-claim"}}]}}}}
    generation: 1
    name: todo-app-dep
    namespace: project
    resourceVersion: "274938"
    uid: 6edbc1e2-1283-40d0-bc8b-0176aa78149e
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: todo-app
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          linkerd.io/inject: enabled
        labels:
          app: todo-app
      spec:
        containers:
        - env:
          - name: PORT
            value: "8080"
          - name: GIN_MODE
            value: release
          image: zhubao/todo-app:latest
          imagePullPolicy: Always
          name: todo-app
          ports:
          - containerPort: 8080
            protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /usr/src/app/files
            name: shared-image
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
  status:
    availableReplicas: 1
    conditions:
    - message: ReplicaSet "todo-app-dep-764868c7bc" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"todo-backend-dep","namespace":"project"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"todo-backend"}},"template":{"metadata":{"labels":{"app":"todo-backend"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"postgres-cfg"}}],"image":"zhubao/todo-backend:latest","name":"todo-backend"}]}}}}
    generation: 1
    name: todo-backend-dep
    namespace: project
    resourceVersion: "275133"
    uid: ec6da75d-5c3e-414c-b9a1-42d90916da94
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: todo-backend
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          linkerd.io/inject: enabled
        labels:
          app: todo-backend
      spec:
        containers:
        - envFrom:
          - configMapRef:
              name: postgres-cfg
          image: zhubao/todo-backend:latest
          imagePullPolicy: Always
          name: todo-backend
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - message: ReplicaSet "todo-backend-dep-6bf9854c84" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata: {}
---
