apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: shared-image
          emptyDir:
            {}
      containers:
        - name: hashgenerator
          image: zhubao/devops-0.2:latest
          imagePullPolicy: Always
          env:
            - name: GENERATE
              value: "true"
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: shared-image
        - name: print-hash
          imagePullPolicy: Always
          image: zhubao/devops-0.2:latest
          env:
            - name: GENERATE
              value: "false"
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: shared-image
