apiVersion: batch/v1
kind: CronJob
metadata:
  name: read-hourly
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          containers:
            - name: read-hourly
              image: zhubao/read-hourly:latest
              command:
                - /bin/sh
                - -c
                - chmod +x script.sh && ./script.sh
          restartPolicy: OnFailure