apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
#images:
#  - name: image
#    newName: zhubao/todo-backend
#    newTag: latest