apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: ping
          image: zhubao/ping-0.1:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: shared-image
