apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gin
  template:
    metadata:
      labels:
        app: gin
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: gin
          image: zhubao/devops_gin_0.1:latest
          env:
            - name: PORT
              value: "9999"
            - name: GIN_MODE
              value: "release"
          ports:
            - containerPort: 9999
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: shared-image
