apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: print-hash
          imagePullPolicy: Always
          image: zhubao/devops-0.2:latest
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: shared-image
