apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo-app
          image: zhubao/todo-app:latest
          env:
            - name: PORT
              value: "8080"
            - name: GIN_MODE
              value: "release"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: shared-image
